### ISSUE TITLE
Feature request: blacklisting websites claiming to be Magisk one

### ISSUE THREAD

**Issue by OneNormalUsername** [Rithari/OnePlusBot#103]
When talking about Magisk, people link to some websites like https://magiskmanager.com/ which claim to be Magisk one while there is no official website and that the only place to download Magisk is https://github.com/topjohnwu/magisk/ 

Even if as of now they do link to Github assets for downloads, nothing proves that they won't become fishy in the future and we also won't keep checking it as it would be a pain to do so.

Blacklisting url by deleting message/warning users that such website is not official when link is sent would be a solution to the issue

**Comment by Rithari** [comment]
Of little actual importance and would open the door for more problems down the road I would rather not get into the specifics of now.
