### ISSUE TITLE
[Feature request] Auto nickname check

### ISSUE THREAD

**Issue by AnonymousWP** [Rithari/OnePlusBot#140]
Implement a feature which detects weird/abnormal characters in someone's name who joined, then ping us in #modqueue for example.

**Comment by Rithari** [comment]
My first implementation of this was a failure, but it would check the entire member list, which was already huge, against a set of illegal characters and would flag said users with a role. 

The checking done when a user joins seems much more plausible and we may be able to direct traffic from it either to the user's DMs or the meta channel, reminding them to change their name.

**Comment by AnonymousWP** [comment]
> My first implementation of this was a failure, but it would check the entire member list, which was already huge, against a set of illegal characters and would flag said users with a role.
> 
> The checking done when a user joins seems much more plausible and we may be able to direct traffic from it either to the user's DMs or the meta channel, reminding them to change their name.

Yeah, but I'd let the bot check in #join-log instead of the entire memberlist. That'll reduce the power and processing it needs in order to execute its task.

**Comment by Rithari** [comment]
That is exactly what I said.
