### ISSUE TITLE
[Feature Request] Slowmode Command

### ISSUE THREAD

**Issue by lavin-a** [Rithari/OnePlusBot#176]
Add a ;slowmode command to enable moderators to toggle slowmode for channels since the permission to edit channels is not granted.

Usage:- 
;slowmode <time 2s-6h> - turns slowmode on with cooldown for the channel it's used in
;slowmode off - turns it off

**Comment by Rithari** [comment]
I'll check out if the library / API supports directly modifying slowmode settings, that should facilitate the whole process.
