### ISSUE TITLE
Automatic message embedding

### ISSUE THREAD

**Issue by Sheldan** [Rithari/OnePlusBot#192]
**Is your feature request related to a problem? Please describe.**
When a user links another message, people need to click on this message and go to that location. 

**Describe the solution you'd like**
It would be convenient to have a solution at when a user posts a message containing a link to another message, this message is embeded. So the content of the message is seen without needing to go to that point in time.

**Comment by Rithari** [comment]
This has been on my mind for months, should be addressed.
