### ISSUE TITLE
[Feature request] Add `;reminders` command

### ISSUE THREAD

**Issue by AnonymousWP** [Rithari/OnePlusBot#205]
**Is your feature request related to a problem? Please describe.**

Yes. For example, if you have set a reminder for 48h or more, you might forget later that you have made a reminder that you might want to delete.

**Describe the solution you'd like**

A `;reminders` command which outputs all your current reminders.

**Additional context**

Not applicable.

**Comment by OneNormalUsername** [comment]
Commenting here as requested: it would be nice to have jump links to those reminders when they are listed as well
