### ISSUE TITLE
Provide easier methods to split up embeds into multiple embeds if needed

### ISSUE THREAD

**Issue by Sheldan** [Rithari/OnePlusBot#207]
**Is your feature request related to a problem? Please describe.**
Embed splitting must be done manually in code, it would be nice to have a mechanism for which we can just define the things which should be contained in the embed and it automatically splits it up into multiple embeds (if necessary).

**Describe the solution you'd like**
Mechanism using iterations defining a current embed build and a list of embeds resulting from the builder. Description should be split up over multiple embeds, fields as well. The content should always start from the very top embed.

**Comment by Rithari** [comment]
Addressed in the [rewrite](https://github.com/Sheldan/OnePlusBot).
