### ISSUE TITLE
Rework the way modmail messages are being logged

### ISSUE THREAD

**Issue by Sheldan** [Rithari/OnePlusBot#224]
**Is your feature request related to a problem? Please describe.**
Currently, when closing, each embed is replayed into the logging channel, which, because for ratelimiting reasons, is delayed. This mechanism causes the logging to take a significant amount.

**Describe the solution you'd like**
Logging mechanism should be changed, so that less messages are needed for logging and the closing of a thread can happen much faster. This  might happen via an attached file to an embed. *Additionally* the close mechanism needs to check whether or not the thread already is getting closed.

**Comment by Rithari** [comment]
Addressed in the [rewrite](https://github.com/Sheldan/OnePlusBot).
