### ISSUE TITLE
Feature request: joining roles (see #suggestion @Discord)

### ISSUE THREAD

**Issue by AnonymousWP** [Rithari/OnePlusBot#23]
The suggestion which has way more 'yes' votes:

"When a user subscribes for a role in #info, make the bot post a message with "you joined role X" in another channel like #bot-firing-range or in PM, so #info doesn't get the 'unread-marker'".

Should be editable in: https://github.com/Rithari/OnePlusBot/blob/master/src/OnePlusBot/Modules/BuildReactTo.cs

**Comment by Rithari** [comment]
The feedback for joining roles is now redundant - so it was completely removed with the arrival for role removal by reaction. 

Thank you for pointing this out,
