### ISSUE TITLE
Racecondition on startup startup for command loading

### ISSUE THREAD

**Issue by Sheldan** [Rithari/OnePlusBot#235]
**Describe the bug**
On startup the commands which are known to the bot are stored in the db for later configuration. At the same time the runtime configuration concerning the disabled commands is loaded. These two mechanisms happen at the same time and there is a race condition at which new commands have not yet been stored and therefore are not known to the runtime configuration which results in the command not being known. 

The current workaround is to reload the database. After this the command is known and this command will not fall into this bug again.

**To Reproduce**
Add a new command and startup bot. Try to use that command. 

**Expected behavior**
Command should not be disabled.

**Comment by Rithari** [comment]
Addressed in the [rewrite](https://github.com/Sheldan/OnePlusBot).
