### ISSUE TITLE
Bot updates role for each level change instead of for each rank change

### ISSUE THREAD

**Issue by OneNormalUsername** [Rithari/OnePlusBot#264]
**Describe the bug**
Bot updates role for each level change.
This spams Discord audit logs entries.

**To Reproduce**
- Use a new account until it gets enough XP to reach level 2 (which is still Cupcake)
- Check audit logs
- Notice that it says that it removed Cupcake role and added it back

**Expected behavior**
- Bot should not update role for each level change but rather for each rank change

**Screenshots**
![image](https://user-images.githubusercontent.com/42769194/76166819-74ee9d80-6159-11ea-8cc7-b8683147e52d.png)

**Comment by Rithari** [comment]
Addressed in the [rewrite](https://github.com/Sheldan/OnePlusBot).
