### ISSUE TITLE
Temporarily unavailable emotes break emotestats display

### ISSUE THREAD

**Issue by Sheldan** [Rithari/OnePlusBot#277]
**Describe the bug**
When the emote is also only temporarily unavailable (because the server lost a boost level, for example) the whole embed in which this emote is displayed breaks down. This causes the emotes to only appear as text. The same thing happens, when the emote was removed from the server, but in this case it was a conscious decision.

**To Reproduce**
Either drop down a boost level, and some emotes become unavailable/remove an emote from the server, while it still exsists in the database and execute `emotestats`, when the emote was used in the heatmap.

**Expected behavior**
Emote should not be rendered, or only the text should be rendered.

**Comment by Rithari** [comment]
Addressed in the [rewrite](https://github.com/Sheldan/OnePlusBot).
