### ISSUE TITLE
Backend updates cause Presence drop

### ISSUE THREAD

**Issue by Rithari** [Rithari/OnePlusBot#89]
Discord API backend updates sometimes cause the bot presence to drop, resulting in the following:

![Screenshot_20190809-062957__01](https://user-images.githubusercontent.com/22421051/62754217-3122a100-ba6f-11e9-81b3-3dea3e1ad836.jpg)

rather than the expected presence of streamed content.

**Comment by Sheldan** [comment]
Can we detect if this happened?

**Comment by Rithari** [comment]
You can easily notice the dropped presence if the bot stops streaming.


A suggested workaround would be a timer to cycle through different, or one, presence states to ensure minimisation of the issue.
